version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - image-base-infer-volume:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - back-api-network

  backend:
    container_name: back-api
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/backend
      - ./_aws:/_aws
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - back-api-network

networks:
  back-api-network:
    driver: bridge

volumes:
  image-base-infer-volume:
