FROM python:3.9

WORKDIR /backend

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir && \
    apt update

CMD ["uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]